### ISSUE TITLE
Version 2.0 - Symfony 2.8 and Symfony 3.0+ compatible only

### ISSUE THREAD

**Issue by slashfan** [lexik/LexikJWTAuthenticationBundle#132]
Hi,

With Symfony 2.3 support coming to an end in May and Symfony 2.8 introducing great new components such as Guard, it would be interesting to create a new major version and drop support for Symfony 2.7 and below. 

That way we could remove all the hack code that tried to maintain compatibility with old Symfony versions, and using using Guard authenticators we could simplify the security layer and provide an out of the box stateless replacement for the form_login.

Any thoughts on this ? It would be great to have your opinion.

Thanks !

-----------

Currently we have those tasks :

- [x] Remove deprecated calls and hacks which maintained compatibility with old symfony versions (#173)
- [x] Remove class parameters from Resource/config/services.xml (#178)
- [x] Provide a more flexible default encoder through supporting SecLib in addition of OpenSSL (#162)
- [x] Avoid injecting Request objects (#200, #201)
- [x] Add functional tests to test the different workflows : anonymous requests, events dispatched, response codes... (#184)
- [x] Use `AppBundle` as namespace for code examples in documentation (#243)
- [ ] Replace legacy security system by Guard Authenticators:
    - [x] JWT token authenticator (#184)
    - [ ] form-login authenticator (#237, closed for now)

Any idea is welcome.

**Comment by lucascherifi** [comment]
:+1:

**Comment by Spomky** [comment]
Hi,

I agree with you. This also implies for PHP 5.4 to be dropped (this version is not supported anymore).

I take the opportunity to introduce you my [jose library](https://github.com/Spomky-Labs/jose) and [bundle](https://github.com/Spomky-Labs/JoseBundle).
At this time these projects are under active developpement, but a stable release is expected by the end of this semester.
Despite the fact that the library is not stable, you will see that it already supports a lot of features, including JWE (encrypted JWT), JWK (keys)/JWKSet (key sets) from different sources (key files, certificates, urls...). All algorithms listed in the [RFC7518](http://tools.ietf.org/html/rfc7518) are supported.
I will be glad if you can take time to check these projects. [We can discuss on these projects](https://gitter.im/Spomky-Labs/jose) if you need more information.

**Comment by weaverryan** [comment]
:+1: @slashfan I'd like to help with the goals of the next release, if you'll have me :). I agree completely with what your initial ideas. What's the next step?

**Comment by slashfan** [comment]
Hi @weaverryan it would be great to have your help ! I think the bundle should provide two main authenticators : 
- a stateless form login (for the first phase authentication by username and password) 
- a  jwt authenticator (for the token based authentication). 

Fortunately, you have already done most of the job in the symfony con presentation you did in december :) 

The idea for the **form login authenticator** is to provide an alternative to the standard symfony form login. It should be stateless and provide out of the box the logic currently provided by the authentication success and failure handlers. The encoder service and the token TTL should be configurable. 

The most important is the **jwt authenticator**. The decoder service and request token extractors services should be configurable. 

Both authenticator should dispatch the current events and provide sensible default configuration.

What's your opinion ? Would you like to work on them ?

**Comment by weaverryan** [comment]
Hi @slashfan!

Yes, this makes sense: there are two steps (getting the token and then using the token), so it's a good plan :).

Would the stateless form login authenticator set the token on a cookie? Or would this be really more of just an "endpoint" that you could hit to return the token as JSON?

If we're providing "Guard authenticator" classes people can use, then naturally, people will have a lot of flexibility.

Unfortunately, I will not have time to personally work on this. I would to help comment and review - but I need someone else in the community to take the reigns! This is an important bundle for Symfony (in fact, it's in a new version of that Guard prez that I'm giving tomorrow).

Thanks!

**Comment by slashfan** [comment]
The stateless form login authenticator is indeed more of an endpoint : if the credentials are good, a json response containing the token is returned; otherwise a a 401 response is returned.

Great, I hope the slides will be available :)

**Comment by weaverryan** [comment]
They are now :) http://www.slideshare.net/weaverryan/symfony-guard-authentication-fun-with-api-token-social-login-jwt-and-more

Cheers!

**Comment by chalasr** [comment]
@weaverryan Thanks for these great slides that give a lots of ideas.

@slashfan I would be glad to help on this way. 
Maybe I can begin to work on the form login authenticator ?

Let me know of where we should start and how you are thinking it, this major release is a really important step.

**Comment by slashfan** [comment]
@chalasr I already have a wip local branch, I'll try to work on it in the next days. In the mean time, if you have some ideas that could improve developer experience or new features in mind let us know. 

I see two things developers often suggest : 
* make the current namshi/jose encoder bridge more flexible by handling the PHPSECLIB and allowing to choose from any algorythm handled by the library (https://github.com/namshi/jose/tree/master/src/Namshi/JOSE/Signer/OpenSSL) 
* ease other jws library integration - maybe by providing local bridges implementing JWTEncoderInterface and adding those libraries to the suggest section of the composer.json ? In that case, the JWTEncoder class should be renamed also.

**Comment by chalasr** [comment]
@slashfan I'm going to start working on the configurable OpenSSL algorithm.
I would implement it through the bundle extension in order to let the user choose one of the available algorithm by setting it as a config option. 

Do you have any suggestions?

**Comment by chalasr** [comment]
@slashfan If you can quickly review my [feature_seclib_openssl_algos branch](https://github.com/chalasr/LexikJWTAuthenticationBundle/commit/cc8cc5d8a3b1e34b3350de44d0845c879ad73db4) and give me your point of view. It's working well! Missing new tests (existing pass!) and documentation.

**Comment by slashfan** [comment]
@chalasr again, very good work you did here ! The only problem I see here is that the old JWTEncoder class is gone (which is necessary) so it could result in problems for developers who extend it or use it directly. It might be time to start a v2 branch while we work on the new (breaking) features.

**Comment by chalasr** [comment]
@slashfan Glad to see that my work is appreciated.
If you think that this could be merged in 1.x by keeping the old JWTEncoder, I can jeep it in place and mark it as deprecated , that would let the time to developers for adapt their code before upgrade to 2.x.where the class would be totally removed.

Note that the interface and the class structure stay intact so extend the new OpenSSLEncoder doesnt involve too much changes.

Let me know if I do the change or if I just update the doc and propose to merge in a 2.x branch (when it is here). 

Thank you

**Comment by slashfan** [comment]
@chalasr It may be cleaner to keep this feature for version two. With proper documentation and testing. Don't you think ?

**Comment by chalasr** [comment]
@slashfan You're right, it's a major change so it needs a major release, and so avoid deprecations.
It would be good if you can create the 2.0 branch so I can quickly submit a PR and mark the task as in progress/done in the 2.0 todo list, then I could enchain on the next tasks.

Do you agree?

**Comment by chalasr** [comment]
I usually do "everything to master at first" and so having branches that represent stables releases.
But, as it surely would be easier to keep clean and because I totally trust you about the way to use it , let's go on. 

However, when it'll be time to release the major `v2.0.0` version (so the new branch is stable), would we merge the new branch in master and so always keep master representing our last major version?

About naming the new branch, that's a really good question...
Naturally I would go on `2.x`, but as we have a different branching model, and depending on your answer to my previous questions, what do you think about use `2.0`?
Like this, we could have a branch per minor release (i.e. branch `2.0` representing the last `v2.0.x` release, branch `2.1` representing the last `v2.1.x` release, ... and master representing the last major release (`v2.0.0` at first).

It looks like nothing but it's an important decision as this next version represents a big step for the bundle.
Thank's to taking care of my opinion @slashfan

**Comment by slashfan** [comment]
@chalasr Sorry for the delay. 

The idea is indeed to merge the new branch into master when it is stable enough and get rid of it afterwards. Maybe we can also create a 1.x branch before merging.

 `2.0` sounds good to me too. I'll create it right away.

**Comment by chalasr** [comment]
:+1:

**Comment by chalasr** [comment]
Reminder:
As pointed in [#162 review](https://github.com/lexik/LexikJWTAuthenticationBundle/pull/162#discussion-diff-60676053L19) and mentioned as [best practice in the symfony doc](http://symfony.com/doc/current/best_practices/business-logic.html#service-no-class-parameter), class parameters should be removed from `Resource/config/services.xml`.

**Comment by slashfan** [comment]
@chalasr Added to the list of todo, thanks

**Comment by chalasr** [comment]
@slashfan Just to be sure, do we stop supporting of Symfony 2.7 and lower versions? I had to make concessions in #162 to keep tests green, it would be interesting if we can avoid them.
If it's ok, I'll remove these versions from the travis configuration and quickly re-add the features needing Symfony 2.8+

**Comment by slashfan** [comment]
2.8 / 3.0+ was the goal since the main idea was to use the Guard component. I know it can be used with 2.7 but it might be too much overhead to maintain 2.7 along with the other versions. What do you think ? @chalasr @weaverryan

**Comment by chalasr** [comment]
@slashfan Supporting 2.7 is possible ATM but could involve (too much) efforts and concessions as long as the bundle evolves. Our 1.x releases are here for that and so, if people want to take benefit of the newer features then they must up Symfony to 2.8 or higher.
As  maintaining a 1.x branch should not be too hard, it seems to be a good compromise to me.

**Comment by weaverryan** [comment]
I'm ok with 2.8+ because it's an LTS and the "old" version of this bundle is still wonderful and will be useable on older versions.

**Comment by slashfan** [comment]
Good, 2.8+ it is !

**Comment by chalasr** [comment]
The v2 has been released. We are looking for feedbacks!
Closing as resolved

**Comment by Spomky** [comment]
Thank you so much @chalasr .
Beside this great news, I take the opportunity to announce you that you introduced in the #233 is now tagged as `v1.0.0`.
This means you can now use it with this new major release as a good alternative to the default encoder.

Thanks also for [the references you added in the documentation](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/1-configuration-reference.md#service). This is really kind of you.
